name: cli53
version: '0.8.17'
summary: Command line tool for Amazon Route 53
description: cli53 provides import and export from BIND format and simple command line management of Route 53 domains.
grade: stable
confinement: strict
base: core18
license: MIT


architectures:
  - build-on: amd64
    run-on: amd64

parts:
  cli53:
    plugin: nil
    override-pull: |
      wget https://github.com/barnybug/cli53/releases/download/${SNAPCRAFT_PROJECT_VERSION}/cli53-linux-amd64
    override-build: |
      snapcraftctl build
      mv cli53-linux-amd64 $SNAPCRAFT_PART_INSTALL/cli53
      chmod +x $SNAPCRAFT_PART_INSTALL/cli53

build-packages:
  - wget

apps: 
  cli53:
    command: cli53
    environment:
      HOME: /home/$USER
    plugs: 
      - home
      - network
      - network-bind
      - network-observe